server:
  port: 8080

spring:
  application:
    name: common-gradle-project
  profiles:
    active: ${DATABASE:postgres},${CUSTOMIZED_PROFILE:customized}
  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB
  # flyway数据库版本控制
  flyway:
    table: flyway_schema_history_cg
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: false
  redis:
    host: ${REDIS_HOST:192.168.239.129}
    port: ${REDIS_PORT:6379}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: ${springdoc.api-docs.enabled}
  api-docs:
    enabled: ${IC_API_DOC:true}
    path: /v3/api-docs
  group-configs:
    - group: 'gradle'
      paths-to-match: '/**'
      packages-to-scan: tech.tongyu.bct
knife4j:
  # 开启增强配置
  enable: ${springdoc.api-docs.enabled}
  basic:
    enable: false
    # Basic认证用户名
    username: tongyu
    # Basic认证密码
    password: tongyu
  setting:
    enableOpenApi: true
  documents:

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: valid
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml


ty:
  info:
    username: test
    pwd: 123
    kiHedgingFun: 1

feign:
  httpclient:
    enabled: true
  client:
    url:
      bct-server: ${BCT_SERVER:http://localhost/bct}
      auth-service: ${BCT_SERVER_AUTH:${feign.client.url.bct-server}}
      trade-service: ${BCT_SERVER_TRADE:${feign.client.url.bct-server}}
      market-data-service: ${BCT_SERVER_MARKET:${feign.client.url.bct-server}}
      capital-service: ${BCT_SERVER_CAPITAL:${feign.client.url.bct-server}}
      exchange-service: ${BCT_SERVER_EXCHANGE:${feign.client.url.bct-server}}
      margin-service: ${BCT_SERVER_MARGIN:${feign.client.url.bct-server}}
      reference-data-service: ${BCT_SERVER_REFERENCE:${feign.client.url.bct-server}}
      pricing-service: ${BCT_SERVER_PRICING:${feign.client.url.bct-server}}
      report-service: ${BCT_SERVER_REPORT:${feign.client.url.bct-server}}
      ic-pybct-server: ${IC_PYBCT_SERVER:http://localhost:5101}